-- TikTokSales Database Schema for Supabase
-- Generated from schema.py with all 9 migrations
-- Run these SQL statements in the Supabase SQL editor

-- =============================================================================
-- Migration 001: Chat Messages
-- =============================================================================
-- Table: chat_messages
-- Purpose: Store all incoming chat messages from live streams
-- Indexes: (streamer, timestamp), (client)

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGSERIAL PRIMARY KEY,
    streamer VARCHAR(255) NOT NULL,
    client VARCHAR(255) NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    message TEXT NOT NULL,
    nlp_intent VARCHAR(50),
    nlp_score FLOAT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_streamer_timestamp 
ON chat_messages(streamer, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_chat_messages_client 
ON chat_messages(client);

CREATE INDEX IF NOT EXISTS idx_chat_messages_nlp_intent 
ON chat_messages(nlp_intent) WHERE nlp_intent IS NOT NULL;

COMMENT ON TABLE chat_messages IS 'All incoming messages from TikTok/stream sources';
COMMENT ON COLUMN chat_messages.nlp_intent IS 'Intent predicted by NLP service (buy, question, none, etc)';
COMMENT ON COLUMN chat_messages.nlp_score IS 'Confidence score of NLP prediction (0-1)';
-- =============================================================================
-- Migration 002: Products
-- =============================================================================
-- Table: products
-- Purpose: Product catalog for matching with Vision service
-- Indexes: (sku), (streamer), (category)

CREATE TABLE IF NOT EXISTS products (
    id BIGSERIAL PRIMARY KEY,
    sku VARCHAR(50) NOT NULL,
    streamer VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    user_description TEXT,  -- Description provided by streamer/seller
    model_description TEXT,  -- Description generated by CV model from images
    price DECIMAL(10, 2) NOT NULL,
    stock INT DEFAULT 0,
    category VARCHAR(100),
    image_urls JSONB,  -- JSON array of {url, filename, size} objects from MinIO
    minio_bucket VARCHAR(255),  -- MinIO bucket name
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(sku, streamer)  -- Same streamer can't have duplicate SKUs
);

CREATE INDEX IF NOT EXISTS idx_products_sku 
ON products(sku);

CREATE INDEX IF NOT EXISTS idx_products_streamer 
ON products(streamer);

CREATE INDEX IF NOT EXISTS idx_products_category 
ON products(category);

CREATE INDEX IF NOT EXISTS idx_products_streamer_sku 
ON products(streamer, sku);

COMMENT ON TABLE products IS 'Product catalog uploaded by streamers for Vision model matching and orders';
COMMENT ON COLUMN products.sku IS 'Stock Keeping Unit - unique identifier per product per streamer';
COMMENT ON COLUMN products.user_description IS 'Product description provided by the streamer/seller';
COMMENT ON COLUMN products.model_description IS 'Auto-generated description from Vision CV model analysis of images';
COMMENT ON COLUMN products.image_urls IS 'JSON array of product images: [{url, filename, size, uploaded_at}]';
COMMENT ON COLUMN products.minio_bucket IS 'MinIO bucket where images are stored';

-- =============================================================================
-- Migration 003: Product Matches (Vision)
-- =============================================================================
-- Table: product_matches
-- Purpose: History of Vision service matches (streamer + timestamp -> product)
-- Purpose: Used to track what products appeared in which streams
-- Indexes: (streamer, timestamp), (product_id)

CREATE TABLE IF NOT EXISTS product_matches (
    id BIGSERIAL PRIMARY KEY,
    streamer VARCHAR(255) NOT NULL,
    stream_timestamp TIMESTAMPTZ NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    vision_score FLOAT,
    frame_urls TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_matches_streamer_timestamp 
ON product_matches(streamer, stream_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_product_matches_product_id 
ON product_matches(product_id);

COMMENT ON TABLE product_matches IS 'Vision service match history: what products appeared in which stream at what time';
COMMENT ON COLUMN product_matches.vision_score IS 'Confidence score from Vision CNN model (0-1)';

-- =============================================================================
-- Migration 004: Orders
-- =============================================================================
-- Purpose: Customer orders created from live stream purchases
-- Indexes: (buyer, created_at), (streamer, created_at), (status)

CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    buyer VARCHAR(255) NOT NULL,
    streamer VARCHAR(255) NOT NULL,
    source VARCHAR(50),  -- 'tiktok_live', 'instagram_live', 'youtube_live', etc
    quantity INT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'pending',  -- pending, paid, shipped, delivered, cancelled
    total_price DECIMAL(10, 2),
    payment_method VARCHAR(50),  -- 'stripe', 'whatsapp_payment', 'sms_payment', etc
    payment_id VARCHAR(255),  -- Stripe transaction ID, etc
    whatsapp_number VARCHAR(20),
    sms_number VARCHAR(20),
    message_sid VARCHAR(255),  -- Twilio message SID
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_buyer 
ON orders(buyer, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_streamer 
ON orders(streamer, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_status 
ON orders(status);

CREATE INDEX IF NOT EXISTS idx_orders_order_number 
ON orders(order_number);

COMMENT ON TABLE orders IS 'Customer orders triggered by live stream shopping events';
COMMENT ON COLUMN orders.source IS 'Platform source: tiktok_live, instagram_live, youtube_live, etc';
COMMENT ON COLUMN orders.status IS 'Order lifecycle: pending -> paid -> shipped -> delivered';
COMMENT ON COLUMN orders.payment_id IS 'External payment processor ID (Stripe transaction, etc)';

-- =============================================================================
-- Migration 005: Chat-Order Mapping
-- =============================================================================
-- Table: chat_message_order_mapping
-- Purpose: Link chat messages to orders for analytics and tracing
-- Purpose: Track which message triggered which order
-- Indexes: (chat_message_id), (order_id)

CREATE TABLE IF NOT EXISTS chat_message_order_mapping (
    id BIGSERIAL PRIMARY KEY,
    chat_message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_message_order_mapping_chat_message_id 
ON chat_message_order_mapping(chat_message_id);

CREATE INDEX IF NOT EXISTS idx_chat_message_order_mapping_order_id 
ON chat_message_order_mapping(order_id);

COMMENT ON TABLE chat_message_order_mapping IS 'Links chat messages to resulting orders for tracing and analytics';

-- =============================================================================
-- Migration 006: Payment Notifications
-- =============================================================================
-- Table: payment_notifications
-- Purpose: Track all payment notification attempts (WhatsApp, SMS)
-- Purpose: Audit trail for compliance
-- Indexes: (order_id), (status), (created_at)

CREATE TABLE IF NOT EXISTS payment_notifications (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    notification_type VARCHAR(50),  -- 'whatsapp', 'sms', 'email', 'in_app'
    recipient_number VARCHAR(20),
    message_sid VARCHAR(255),  -- Twilio SID
    status VARCHAR(50),  -- 'sent', 'failed', 'read', 'unread'
    retry_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_notifications_order_id 
ON payment_notifications(order_id);

CREATE INDEX IF NOT EXISTS idx_payment_notifications_status 
ON payment_notifications(status);

CREATE INDEX IF NOT EXISTS idx_payment_notifications_created_at 
ON payment_notifications(created_at DESC);

COMMENT ON TABLE payment_notifications IS 'Audit trail for payment notifications sent to customers';

-- =============================================================================
-- Migration 007: Streamers
-- =============================================================================
-- Table: streamers
-- Purpose: Store streamer profiles and configuration
-- Indexes: (username)

CREATE TABLE IF NOT EXISTS streamers (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    platform VARCHAR(50),  -- 'tiktok', 'instagram', 'youtube'
    follower_count INT,
    total_sales DECIMAL(12, 2) DEFAULT 0,
    commission_percentage DECIMAL(5, 2) DEFAULT 5.0,
    payment_method VARCHAR(50),  -- 'bank_transfer', 'paypal', 'stripe'
    payment_account VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_streamers_username 
ON streamers(username);

CREATE INDEX IF NOT EXISTS idx_streamers_platform 
ON streamers(platform);

COMMENT ON TABLE streamers IS 'Influencer/streamer profiles for commission tracking';

-- =============================================================================
-- Migration 008: NLP Intents
-- =============================================================================
-- Table: nlp_intents
-- Purpose: Master list of intent types for NLP model
-- Purpose: Analytics on user intent distribution

CREATE TABLE IF NOT EXISTS nlp_intents (
    id BIGSERIAL PRIMARY KEY,
    intent_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO nlp_intents (intent_name, description) VALUES
('buy', 'User expresses intent to purchase the product'),
('question', 'User asks about product features, price, shipping, etc'),
('feedback', 'User provides positive or negative feedback'),
('none', 'No clear intent detected'),
('complaint', 'User complains about product or service')
ON CONFLICT DO NOTHING;

COMMENT ON TABLE nlp_intents IS 'Master list of intent types for NLP classification';

-- =============================================================================
-- Migration 009: Streamer Frames
-- =============================================================================
-- Table: streamer_frames
-- Purpose: Periodically-captured frames from streamers stored in MinIO
-- Indexes: (streamer, frame_timestamp)

CREATE TABLE IF NOT EXISTS streamer_frames (
    id BIGSERIAL PRIMARY KEY,
    streamer VARCHAR(255) NOT NULL,
    frame_timestamp TIMESTAMPTZ NOT NULL,
    minio_url TEXT NOT NULL,
    minio_object VARCHAR(1024) NOT NULL,
    content_type VARCHAR(128),
    width INT,
    height INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_streamer_frames_streamer_timestamp
ON streamer_frames(streamer, frame_timestamp DESC);

COMMENT ON TABLE streamer_frames IS 'Individual frames captured from streamers video feeds and stored in MinIO';
COMMENT ON COLUMN streamer_frames.minio_url IS 'S3/MinIO URL stored as minio://bucket/object or http(s) presigned URL';

-- =============================================================================
-- End of migrations
-- =============================================================================


-- =============================================================================
-- Migration 010: Clients
-- =============================================================================
-- Table: clients
-- Purpose: Registered customers who can purchase across multiple streamers

CREATE TABLE IF NOT EXISTS clients (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash TEXT NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clients_email ON clients(email);

COMMENT ON TABLE clients IS 'Registered customers (buyers) for the TikTokSales platform';

-- =============================================================================
-- Migration 011: Orders - add buyer_id
-- =============================================================================
-- Purpose: Add optional buyer_id FK to orders to link to `clients` table

ALTER TABLE IF EXISTS orders
ADD COLUMN IF NOT EXISTS buyer_id BIGINT;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'clients') THEN
        BEGIN
            ALTER TABLE orders ADD CONSTRAINT fk_orders_buyer_id FOREIGN KEY (buyer_id) REFERENCES clients(id);
        EXCEPTION WHEN duplicate_object THEN
            NULL;
        END;
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_orders_buyer_id ON orders(buyer_id);

COMMENT ON COLUMN orders.buyer_id IS 'Optional FK to clients.id for registered customers';


